
/*******************************************************************************
* generated by lcd-image-converter rev.e3ba1ed from 2025-01-31 18:27:03 +0500
* image
* filename: unsaved
* name: _50_percent_14_50
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Threshold Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_OilLevel_50[100] = {
    // ██████████████
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙█
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    0xff, 0xfc, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0x80, 0x04, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc, 0xff, 0xfc
};
